In [1]:
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import numpy as np
import pandas as pd
import os
import networkx as nx
import pickle
import sys

import pyphi
from pyphi import actual, config, Direction
pyphi.config.VALIDATE_SUBSYSTEM_STATES = False
pyphi.config.PARTITION_TYPE = 'TRI'

# Change directory to where packages are stored
os.chdir("..")

from pyanimats import *
from pyTPM import *
import actual_agency as agency
os.chdir("Example")


#%matplotlib inline
#%load_ext autoreload
#%autoreload 2
#%aimport pyTPM, pyanimats, actual_agency


Welcome to PyPhi!

If you use PyPhi in your research, please cite the paper:

  Mayner WGP, Marshall W, Albantakis L, Findlay G, Marchman R, Tononi G.
  (2018). PyPhi: A toolbox for integrated information theory.
  PLOS Computational Biology 14(7): e1006343.
  https://doi.org/10.1371/journal.pcbi.1006343

Documentation is available online (or with the built-in `help()` function):
  https://pyphi.readthedocs.io

To report issues, please use the issue tracker on the GitHub repository:
  https://github.com/wmayner/pyphi

For general discussion, you are welcome to join the pyphi-users group:
  https://groups.google.com/forum/#!forum/pyphi-users

To suppress this message, either:
  - Set `WELCOME_OFF: true` in your `pyphi_config.yml` file, or
  - Set the environment variable PYPHI_WELCOME_OFF to any value in your shell:
        export PYPHI_WELCOME_OFF='yes'



In [2]:
path='/Users/bjornjuel/projects/mabe_update/mabe/Experiments'
experiment_list=['deterministic_1-7','deterministic_1-3-15-7','combined_1-7','combined_1-3-15-7']
file_names=['genome.pkl','activity.pkl','LOD_data.pkl']
gate_types=[['deterministic'],['deterministic'],['deterministic','decomposable'],['deterministic','decomposable']]

In [ ]:
dats = agency.load_data(path,experiment_list,gate_types=gate_types)

In [ ]:
# parse and pickle data
with open('/Users/bjornjuel/projects/mabe_update/mabe/Experiments/loaded_data.pkl', 'wb') as f:
        pickle.dump(dats, f)

In [32]:
# Load already pickled data
with open('/Users/bjornjuel/projects/mabe_update/mabe/Experiments/loaded_data.pkl', 'rb') as f:
    dats = pickle.load(f)

In [4]:
e = 0
r = 0
a = 0


dats.loc[(dats['Experiment']=='deterministic_1-7') & (dats['Run']==r) & (dats['agent']==a)]['animat'][0]
ani = dats.loc[(dats['Experiment']=='deterministic_1-7') & (dats['Run']==r) & (dats['agent']==a)]['animat'][0]

In [ ]:
x,y = agency.get_occurrences(ani.brain_activity,2,4,2)

In [ ]:
x.shape

In [9]:
u,nn = agency.get_all_unique_transitions(ani.brain_activity)

In [ ]:
ani.saveUniqueTransitions()

In [31]:
dats

Experiment  Run  agent                                    animat  \
0   deterministic_1-7    0      0  <pyanimats.Animat object at 0x1072e21d0>   
0   deterministic_1-7    0      1  <pyanimats.Animat object at 0x12274e2d0>   
0   deterministic_1-7    0      2  <pyanimats.Animat object at 0x12274e5d0>   
0   deterministic_1-7    0      3  <pyanimats.Animat object at 0x12274e8d0>   
0   deterministic_1-7    0      4  <pyanimats.Animat object at 0x12274eb90>   
..                ...  ...    ...                                       ...   
0   combined_1-3-15-7   49     56  <pyanimats.Animat object at 0x1c0c95190>   
0   combined_1-3-15-7   49     57  <pyanimats.Animat object at 0x1c0c95490>   
0   combined_1-3-15-7   49     58  <pyanimats.Animat object at 0x1c0c95790>   
0   combined_1-3-15-7   49     59  <pyanimats.Animat object at 0x1c0c95a90>   
0   combined_1-3-15-7   49     60  <pyanimats.Animat object at 0x1c0c95d90>   

     fitness  n_nodes  n_sensor  n_motor  n_hidden  connected nodes max Phi  \
0   0.515625        8         2        2         4                3     TBD   
0   0.781250        8         2        2         4                3     TBD   
0   0.781250        8         2        2         4                3     TBD   
0   0.781250        8         2        2         4                3     TBD   
0   0.781250        8         2        2         4                3     TBD   
..       ...      ...       ...      ...       ...              ...     ...   
0   0.890625        8         2        2         4                4     TBD   
0   0.882812        8         2        2         4                4     TBD   
0   0.890625        8         2        2         4                4     TBD   
0   0.890625        8         2        2         4                4     TBD   
0   0.890625        8         2        2         4                4     TBD   

   mean Phi max distinctions mean distinctions DC purview length  \
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
..      ...              ...               ...               ...   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   
0       TBD              TBD               TBD               TBD   

   DC total alpha DC hidden ratio CC length  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
..            ...             ...       ...  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  
0             TBD             TBD       TBD  

[8540 rows x 18 columns]

In [10]:
u

[(array([1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 1., 1., 1., 0., 0.])),
 (array([1., 0., 0., 0., 1., 1., 0., 0.]),
  array([0., 0., 0., 1., 1., 1., 1., 0.])),
 (array([1., 0., 0., 0., 1., 1., 1., 0.]),
  array([0., 0., 1., 1., 1., 0., 1., 0.])),
 (array([0., 0., 0., 0., 1., 0., 1., 0.]),
  array([0., 0., 1., 1., 1., 0., 0., 0.])),
 (array([0., 0., 0., 0., 1., 0., 0., 0.]),
  array([0., 0., 0., 1., 1., 1., 0., 0.])),
 (array([0., 0., 0., 0., 1., 1., 0., 0.]),
  array([0., 0., 0., 1., 1., 1., 1., 0.])),
 (array([0., 0., 0., 0., 1., 1., 1., 0.]),
  array([0., 0., 1., 1., 1., 0., 1., 0.])),
 (array([0., 1., 0., 0., 1., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0., 0., 1.])),
 (array([0., 1., 0., 0., 0., 0., 0., 1.]),
  array([0., 0., 0., 1., 1., 1., 0., 1.])),
 (array([0., 1., 0., 0., 1., 1., 0., 1.]),
  array([0., 0., 0., 1., 1., 0., 1., 1.])),
 (array([0., 1., 0., 0., 1., 0., 1., 1.]),
  array([0., 0., 1., 1., 0., 1., 0., 1.])),
 (array([0., 0., 0., 0., 0., 1., 0., 1.]),


In [8]:
ani.UniqueStates

[[1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 1, 1, 0, 1, 1],
 [0, 0, 0, 1, 1, 1, 0, 0],
 [1, 0, 0, 1, 1, 1, 0, 0],
 [0, 0, 0, 1, 1, 1, 1, 0],
 [1, 0, 0, 1, 1, 1, 1, 0],
 [0, 0, 0, 1, 1, 1, 0, 1],
 [0, 0, 0, 1, 1, 1, 1, 1],
 [0, 0, 1, 1, 0, 1, 0, 1],
 [0, 0, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 1, 0, 1, 0],
 [0, 0, 1, 1, 1, 0, 1, 0],
 [1, 0, 1, 1, 1, 1, 0, 1],
 [0, 0, 1, 1, 1, 1, 0, 1],
 [0, 0, 1, 1, 1, 1, 1, 1],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 1, 1, 1, 1],
 [0, 1, 0, 1, 0, 0, 0, 1],
 [1, 1, 0, 1, 0, 0, 1, 1],
 [0, 1, 0, 1, 0, 0, 1, 1],
 [0, 1, 0, 1, 1, 0, 1, 1],
 [0, 1, 0, 1, 1, 1, 0, 0],
 [0, 1, 0, 1, 1, 1, 0, 1],
 [0, 1, 0, 1, 1, 1, 1, 0],
 [1, 1, 0, 1, 1, 1, 0, 1],
 [0, 1, 0, 1, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 0, 0, 0],
 [1, 1, 0, 1, 1, 1, 0, 0],
 [1, 1, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 0, 1, 0],
 [0, 1, 1, 1, 0, 1, 0, 1],
 [1, 1, 1, 1, 0, 1, 0, 1],
 

In [16]:
# for analysis, lets pick a single animat (can be looped over)
Experiment = 'combined_1-7'
Run = 10
Agent = 60

ani = dats.loc[(dats['Experiment']==Experiment) & (dats['agent']==Agent) & (dats['Run']==Run)]['animat'][0]


In [18]:
# calculate phi and complex for every unique state

# first get all unique states
ani.UniqueStates,ani.UniqueStataeNums = agency.get_unique_states(ani.brain_activity)

# looping through all unique states
IIT_vals = []
allphis = []
allconcepts = []
allsize = []
alllabels = []
for s in ani.UniqueStates:
    sia = pyphi.compute.complexes(ani.brain,s)
    
    state_vals = []
    if len(sia)>0:
        for c in sia:
            allphis.append(c.phi)
            allconcepts.append(len(c.ces.mechanisms))
            allsize.append(len(c.subsystem.node_indices))
            alllabels.append(c.subsystem.node_indices)
            IIT_vals
    else:
        
    


In [ ]:
# give the animat object a complex and a value of phi associated to every state in its activity




In [ ]:
# calculate direct cause for motor activity for every unique transition 




In [ ]:
# Backtrack the causes of action for every motor state and add result to the animat structure




In [29]:
s = ani.UniqueStates[0]
s


Computing concepts:  14%|█▍        | 1/7 [00:00<00:00,  9.22it/s]
                                                                 
Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]


In [30]:
out

[]

In [22]:
dats.loc[(dats['Experiment']==Experiment) & (dats['agent']==Agent) & (dats['Run']==Run)]['mean Phi'][0]

'TBD'

In [28]:
ani.brain

Network([[[[[[[[[0.5 0.5 0.  ... 1.  0.  0. ]
        [0.5 0.5 0.  ... 1.  0.  0. ]]

       [[0.5 0.5 1.  ... 1.  0.  0. ]
        [0.5 0.5 1.  ... 1.  0.  0. ]]]


      [[[0.5 0.5 0.  ... 1.  1.  0. ]
        [0.5 0.5 0.  ... 1.  1.  0. ]]

       [[0.5 0.5 1.  ... 1.  1.  0. ]
        [0.5 0.5 1.  ... 1.  1.  0. ]]]]



     [[[[0.5 0.5 0.  ... 1.  0.  0. ]
        [0.5 0.5 0.  ... 1.  0.  0. ]]

       [[0.5 0.5 1.  ... 0.  0.  0. ]
        [0.5 0.5 1.  ... 0.  0.  0. ]]]


      [[[0.5 0.5 0.  ... 1.  1.  0. ]
        [0.5 0.5 0.  ... 1.  1.  0. ]]

       [[0.5 0.5 1.  ... 0.  1.  0. ]
        [0.5 0.5 1.  ... 0.  1.  0. ]]]]]




    [[[[[0.5 0.5 0.  ... 1.  0.  0. ]
        [0.5 0.5 0.  ... 1.  0.  0. ]]

       [[0.5 0.5 1.  ... 1.  0.  0. ]
        [0.5 0.5 1.  ... 1.  0.  0. ]]]


      [[[0.5 0.5 0.  ... 1.  1.  0. ]
        [0.5 0.5 0.  ... 1.  1.  0. ]]

       [[0.5 0.5 1.  ... 1.  1.  0. ]
        [0.5 0.5 1.  ... 1.  1.  0. ]]]]



     [[[[0.5 0.5 0.  ... 1.  0.  0. 